### ISSUE TITLE
Relative highlighting

### ISSUE THREAD

**Issue by Vitruvia** [tjdevries/overlength.vim#1]
Is there an easy way to make the highlighting relative to the textwidth, but not exactly the textwidth? For example if textwidth = 78 `set overlength#relative_highlight = +4` would highlight word only when they reach length 82. and `set overlength#relative_highlight = -4` would highlight words at 74 columns. 

I'm asking this because using `gq` sometimes formats words to be exactly equal the textwidth, which causes the last letter to be highlighted. But I think overall it would be a nice feature to have.

**Comment by tjdevries** [comment]
There is not currently, but I will look into it :)

**Comment by tjdevries** [comment]
What if I just highlight starting at &textwidth + 1

**Comment by Vitruvia** [comment]
I think that solves it. The way I put it would make it more customizable but maybe it wouldn't even be useful. +1 should be enough for most cases.

**Comment by tjdevries** [comment]
Let me know if that doesn't fix it.

I added `overlength#default_grace_length` and defaulted it to 1
