### ISSUE TITLE
Sometimes highlighting fails

### ISSUE THREAD

**Issue by onlycalm** [tjdevries/overlength.vim#3]
For some wide characters, sometimes highlighting fails. Such as Chinese

**Comment by Calm-cpy** [comment]
![Uploading 2020-03-23_14-08-05.png…]()

**Comment by onlycalm** [comment]
![2020-03-23_14-08-05](https://user-images.githubusercontent.com/48640489/77287314-3a1b6680-6d10-11ea-9d9c-af6c84d8088d.png)

When ASCII characters and Chinese characters appear in a line at the same time, deleting a certain number of ASCII characters may or may not be highlighted

**Comment by tjdevries** [comment]
Can you send me the text of the lines that aren't highlighting? I'll try to reproduce and then fix. Thanks for reporting the issue (and glad to know some people are using this :smile: )

**Comment by onlycalm** [comment]
I didn't reply in time due to the time difference. The test text is as follows：
#define BT1_TIMING_1_2216ms             55762u                 //! Beacon提前1.5个周期唤醒，为TDEL做准备。唤醒后并不立刻停止打码。
#define BT1_TIMING_1_2216ms             55762u                 //!< Beacon提前.5个周期唤醒，为TDEL做准备。唤醒后并不立刻停止打码。
#define BT1_TIMING_1_2216ms             55762u                 //!< Beacon提前1.5周期唤醒，为TDEL做准备。唤醒后并不立刻停止打码。
#define BT1_TIMING_1_2216ms             55762u                 //!< Beacon提前1.5个周期唤醒，为TDEL做准备。唤醒后并不立刻停止打码。
#define BT1_TIMING_1_2216ms             55762u                 //!< Beacon提前1.个周期唤醒，为TDEL做准备。唤醒后并不立刻停止打码。

Thanks

**Comment by tjdevries** [comment]
No problem :)

What is your textwidth set for the file? Thanks for replying.

**Comment by tjdevries** [comment]
Ha, figured it out. Pretty funny bug w/ double-wide unicode characters. I should have read the docs better. Will push a fix shortly.

**Comment by onlycalm** [comment]
All my configurations are as follows: 
```
set encoding=utf-8
set fileencodings=utf-8,chinese,latin-1
if has("win32")
set fileencoding=chinese
else
set fileencoding=utf-8
endif
    
"Prevent the Chinese code of the GUI right-click menu from garbled
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim

language messages zh_CN.utf-8
```
Looking forward to the new version, thank you!

**Comment by tjdevries** [comment]
![image](https://user-images.githubusercontent.com/4466899/77380464-7de29000-6d51-11ea-9ef0-62f596c9bb4c.png)

**Comment by tjdevries** [comment]
I've uploaded the new version, can you tell me if it does what you wanted?

**Comment by onlycalm** [comment]
Yes, this bug has been fixed. It works very well

**Comment by tjdevries** [comment]
Great :grin: Glad you're using the plugin. Let me know if there are any other features you'd like to see :) I'll close this issue then!

Feel free to check out my other plugins too :stuck_out_tongue_closed_eyes:
