### ISSUE TITLE
no variable definition error: default_grace_length

### ISSUE THREAD

**Issue by roachsinai** [tjdevries/overlength.vim#4]
I add below setting

```
" Disable highlighting in markdown.
call overlength#set_overlength('markdown', 0)
```

got error:

```
处理 function overlength#set_overlength[3]..overlength#highlight 时发生错误:
第    9 行:
E121: 未定义的变量: g:overlength#default_grace_length
```

which means `g:overlength#default_grace_length` not defined at https://github.com/tjdevries/overlength.vim/blob/cd8d3649cce72ba7184a2afb4bbbf07a48b8039c/autoload/overlength.vim#L105

There is no default value for it.

**Comment by tjdevries** [comment]
Hmm, that's pretty weird. I have it getting defined in `plugin/overlength.vim`. I've added `g:` prefixes to be explicit on the setting (in case somehow they are getting sourced in a unique way) and added a check in the function to use a default. Should be fixed now (although I'm not sure how it happened originally).

Thanks for reporting!

**Comment by roachsinai** [comment]
Yeah, no error for now.

**Comment by tjdevries** [comment]
Okay great, thanks for reporting back :)
