### ISSUE TITLE
[feature] blacklist support.

### ISSUE THREAD

**Issue by roachsinai** [tjdevries/overlength.vim#5]
If so not need write multilines for all these filetypes, like: diff, git, floggraph, markdown, etc.

**Comment by tjdevries** [comment]
Does the newest commit give a sufficient solution?

```vim
" To disable highlighting in multiple fts at once
call overlength#disable_filetypes(['markdown', 'term'])
```

**Comment by roachsinai** [comment]
Yeah, it does. Thanks.
